# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'case.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import http.client
import hashlib
import json
import urllib
import random
from PyQt5.Qt import QIcon

class Ui_human_translation(object):
    def setupUi(self, human_translation):
        human_translation.setObjectName("human_translation")
        human_translation.resize(1060, 784)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        human_translation.setFont(font)
        self.centralwidget = QtWidgets.QWidget(human_translation)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 400, 120, 30))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 330, 81, 30))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(280, 415, 750, 330))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(280, 50, 750, 330))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.translation = QtWidgets.QPushButton(self.centralwidget)
        self.translation.setGeometry(QtCore.QRect(790, 320, 100, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.translation.setFont(font)
        self.translation.setObjectName("translation")
        self.human_translation_2 = QtWidgets.QPushButton(self.centralwidget)
        self.human_translation_2.setGeometry(QtCore.QRect(910, 320, 100, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.human_translation_2.setFont(font)
        self.human_translation_2.setObjectName("human_translation_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 100, 201, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(110, 40, 50, 50))
        self.logo.setObjectName("logo")
        self.bgcolor = QtWidgets.QLabel(self.centralwidget)
        self.bgcolor.setGeometry(QtCore.QRect(250, 0, 831, 791))
        self.bgcolor.setText("")
        self.bgcolor.setObjectName("bgcolor")
        self.logo1 = QtWidgets.QLabel(self.centralwidget)
        self.logo1.setGeometry(QtCore.QRect(60, 190, 30, 30))
        self.logo1.setObjectName("logo1")
        self.logo2 = QtWidgets.QLabel(self.centralwidget)
        self.logo2.setGeometry(QtCore.QRect(60, 260, 30, 30))
        self.logo2.setObjectName("logo2")
        self.logo4 = QtWidgets.QLabel(self.centralwidget)
        self.logo4.setGeometry(QtCore.QRect(60, 400, 30, 30))
        self.logo4.setObjectName("logo4")
        self.logo3 = QtWidgets.QLabel(self.centralwidget)
        self.logo3.setGeometry(QtCore.QRect(60, 330, 30, 30))
        self.logo3.setObjectName("logo3")
        self.logo5 = QtWidgets.QLabel(self.centralwidget)
        self.logo5.setGeometry(QtCore.QRect(60, 530, 150, 150))
        self.logo5.setObjectName("logo5")
        self.bgcolor1 = QtWidgets.QLabel(self.centralwidget)
        self.bgcolor1.setGeometry(QtCore.QRect(0, 245, 250, 60))
        self.bgcolor1.setText("")
        self.bgcolor1.setObjectName("bgcolor1")
        self.dictionary1 = QtWidgets.QPushButton(self.centralwidget)
        self.dictionary1.setGeometry(QtCore.QRect(110, 190, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dictionary1.setFont(font)
        self.dictionary1.setObjectName("dictionary1")
        self.dictionary2 = QtWidgets.QPushButton(self.centralwidget)
        self.dictionary2.setGeometry(QtCore.QRect(110, 260, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dictionary2.setFont(font)
        self.dictionary2.setObjectName("dictionary2")
        self.prompt = QtWidgets.QLabel(self.centralwidget)
        self.prompt.setGeometry(QtCore.QRect(280, 10, 340, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.prompt.setFont(font)
        self.prompt.setObjectName("prompt")
        self.bgcolor1.raise_()
        self.bgcolor.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.textBrowser.raise_()
        self.textEdit.raise_()
        self.translation.raise_()
        self.human_translation_2.raise_()
        self.label_5.raise_()
        self.logo.raise_()
        self.logo1.raise_()
        self.logo4.raise_()
        self.logo3.raise_()
        self.logo5.raise_()
        self.logo2.raise_()
        self.dictionary1.raise_()
        self.dictionary2.raise_()
        self.prompt.raise_()
        human_translation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(human_translation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 23))
        self.menubar.setObjectName("menubar")
        human_translation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(human_translation)
        self.statusbar.setObjectName("statusbar")
        human_translation.setStatusBar(self.statusbar)

        self.retranslateUi(human_translation)
        QtCore.QMetaObject.connectSlotsByName(human_translation)

    def retranslateUi(self, human_translation):
        _translate = QtCore.QCoreApplication.translate
        human_translation.setWindowTitle(_translate("human_translation", "翻译系统"))
        self.setWindowIcon(QIcon('..\img\Icon.GIF'))
        self.label_4.setText(_translate("human_translation", "文档翻译"))
        self.label_3.setText(_translate("human_translation", "单词本"))
        self.translation.setText(_translate("human_translation", "翻 译"))
        self.human_translation_2.setText(_translate("human_translation", "人工翻译"))
        self.label_5.setText(_translate("human_translation", "中英文翻译系统"))
        self.logo.setText(_translate("human_translation", "logo"))
        self.logo1.setText(_translate("human_translation", "logo1"))
        self.logo2.setText(_translate("human_translation", "logo2"))
        self.logo4.setText(_translate("human_translation", "logo4"))
        self.logo3.setText(_translate("human_translation", "logo3"))
        self.logo5.setText(_translate("human_translation", "logo5"))
        self.dictionary1.setText(_translate("human_translation", "词典"))
        self.dictionary2.setText(_translate("human_translation", "翻译"))

